import { Text, Image, Button, Flex } from "@mantine/core";
import { child } from "firebase/database";
import Head from "next/head";
import { type } from "os";
import { useRef } from "react";
import { database, ref, set, get, push, onValue } from "../database/config_database"

type NewWord = {
  id: string;
  word: string;
  translation: string;
  image: string;
}

let testNewWord: NewWord [] = [
  {
    id: '101',
    word: 'New',
    translation: 'Novo',
    image: 'www.image.com'
  },
  {
    id: '102',
    word: 'Girl',
    translation: 'Garota',
    image: 'www.image.com'
  },
  {
    id: '103',
    word: 'Boy',
    translation: 'Menino',
    image: 'www.image.com'
  },
]

export default function Home() {
  const audioRef = useRef<HTMLAudioElement>(null)

  const playAudio = () => {
    if (audioRef.current) {
      audioRef.current.play()
    }
  }

  function writeData(userId: any, newWord: NewWord []) {
    const db = database;
    set(ref(db, 'users/' + userId), {
      newWord
    })
  }
  writeData("Alexsandro", testNewWord ) 

  function readData() {
    const dbRef = ref(database)
    get(child(dbRef, "/users")).then((snapshot: any) => {
      if (snapshot.exists()) {
        console.log(snapshot.val())
      } else {
        console.log("no data available")
      }
    }).catch((error:any) => {
      console.error(error)
    })
  }
  readData()

  return (
    <>
      <Head>
        <title>Learn English Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>Home</Text>
      
      <Flex
        direction="column" 
        maw={240}
      >
        <Image
          src="https://firebasestorage.googleapis.com/v0/b/letmeask-333417.appspot.com/o/guava.jpg?alt=media&token=f99814cc-c0e7-425d-b028-fa16e73afe73"
          height={220}
          radius="md"
          mx="auto"
          fit="contain" 
          alt="Norway"
        /> 

        <audio ref={audioRef}>
          <source src="https://firebasestorage.googleapis.com/v0/b/letmeask-333417.appspot.com/o/guava.mp3?alt=media&token=9954a02d-e0cd-4010-b78d-3f91809b9391" />
        </audio>
       
        <Button onClick={playAudio} variant="light" color="blue" fullWidth mt="md" radius="md">
          Guava
        </Button>
      </Flex>

    </>
  )
}
